apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volunteer-service
  namespace: argocd
spec:
  project: default
  source:
    # Verificar se essa é mesmo a URL final do repositório antes do primeiro apply.
    repoURL: https://github.com/nascied/fiap-tech-challenge-fase-5-gitops
    targetRevision: main
    path: helm/volunteer-service
  destination:
    server: https://kubernetes.default.svc
    namespace: fiap-tc-f5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
